
# User Section
### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "admin@gmail.com",
  "password": "somepass"
}

### Sign In
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "admin@gmail.com",
  "password": "somepass"
}

### Whoami
GET http://localhost:3000/auth/whoami
content-type: application/json


### Sign out
POST http://localhost:3000/auth/signout
content-type: application/json


# Reports Section
### Create Report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "year": 1986,
  "mileage": 20000,
  "lng": 0,
  "lat": 0,
  "price": 4500
}

### Approve Report
PATCH  http://localhost:3000/reports/5d8d75d2-b79d-4add-94d0-cdda6ce8afe0
content-type: application/json

{
  "approved": false
}

