
# User Section
### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "admin@gmail.com",
  "password": "somepass"
}


### Whoami
GET http://localhost:3000/auth/whoami
content-type: application/json


### Sign out
POST http://localhost:3000/auth/signout
content-type: application/json


# Reports Section
### Create Report
POST http://localhost:3000/reports
content-type: application/json

{
  "make": "ford",
  "model": "mustang",
  "year": 2000,
  "mileage": 20000,
  "lng": 0,
  "lat": 0,
  "price": 20000
}

### Approve Report
PATCH  http://localhost:3000/reports/7b459362-d840-4fa3-ba04-f7984772f7ad		
content-type: application/json

{
  "approved": true
}

### Sign In
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "admin@gmail.com",
  "password": "somepass"
}


### Get Estimate Report
GET  http://localhost:3000/reports?make=ford&model=mustang&year=2000&mileage=20000&lat=0&lng=0
content-type: application/json

