### Sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "ellipe+bertel2@gmail.com",
  "password": "somepass"
}

### Sign In
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "ellipe+bertel2@gmail.com",
  "password": "somepass"
}

### Whoami
GET http://localhost:3000/auth/whoami
content-type: application/json


### Sign out
POST http://localhost:3000/auth/signout
content-type: application/json
